"""Secure storage and public metadata for files generated by TexDEV."""
from __future__ import annotations

import json
import re
import shutil
import uuid
import os
from pathlib import Path
from urllib.parse import quote

import requests

ARTIFACT_DIR = (Path(os.getenv("TEXDEV_ARTIFACT_DIR", "/tmp/texengine-artifacts" if os.getenv("VERCEL") else Path(__file__).resolve().parents[1] / "workspace" / "artifacts"))).resolve()
MIME_TYPES = {
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "txt": "text/plain; charset=utf-8",
    "md": "text/markdown; charset=utf-8",
    "py": "text/x-python; charset=utf-8",
    "json": "application/json",
    "tsx": "text/typescript; charset=utf-8",
    "ts": "text/typescript; charset=utf-8",
    "jsx": "text/javascript; charset=utf-8",
    "js": "text/javascript; charset=utf-8",
    "css": "text/css; charset=utf-8",
    "html": "text/html; charset=utf-8",
    "yml": "text/yaml; charset=utf-8",
    "yaml": "text/yaml; charset=utf-8",
    "ps1": "text/plain; charset=utf-8",
    "php": "text/plain; charset=utf-8",
    "rb": "text/plain; charset=utf-8",
    "swift": "text/plain; charset=utf-8",
    "kt": "text/plain; charset=utf-8",
    "sql": "text/plain; charset=utf-8",
    "c": "text/plain; charset=utf-8",
    "cpp": "text/plain; charset=utf-8",
    "cs": "text/plain; charset=utf-8",
    "sh": "text/plain; charset=utf-8",
    "rs": "text/plain; charset=utf-8",
    "go": "text/plain; charset=utf-8",
    "r": "text/plain; charset=utf-8",
    "dart": "text/plain; charset=utf-8",
    "scala": "text/plain; charset=utf-8",
    "lua": "text/plain; charset=utf-8",
    "pl": "text/plain; charset=utf-8",
    "toml": "text/plain; charset=utf-8",
    "obj": "text/plain; charset=utf-8",
    "mtl": "text/plain; charset=utf-8",
    "blend": "application/octet-stream",
    "stl": "model/stl",
    "ply": "application/octet-stream",
    "gltf": "model/gltf+json",
    "glb": "model/gltf-binary",
    "txt": "text/plain; charset=utf-8",
}


def safe_filename(value: str, extension: str) -> str:
    stem = Path(str(value or "Generated file")).stem
    stem = re.sub(r"[^A-Za-z0-9 _-]", "", stem).strip(" ._- ")[:80] or "Generated file"
    return f"{stem}.{extension}"


def register_artifact(source: Path, filename: str | None = None, artifact_type: str | None = None, language: str | None = None) -> dict:
    source = source.resolve()
    if not source.is_file():
        raise FileNotFoundError("Generated file does not exist.")
    extension = source.suffix.lower().lstrip(".")
    if not extension:
        extension = "txt"
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    artifact_id = uuid.uuid4().hex
    stored = ARTIFACT_DIR / f"{artifact_id}.{extension}"
    shutil.copyfile(source, stored)
    display_name = safe_filename(filename or source.name, extension)
    metadata = {"id": artifact_id, "artifact_type": artifact_type or extension, "filename": display_name, "download_url": f"/api/artifacts/{artifact_id}", "storage_path": f"{artifact_id}.{extension}"}
    if language:
        metadata["language"] = language
    (ARTIFACT_DIR / f"{artifact_id}.json").write_text(json.dumps(metadata), encoding="utf-8")
    _upload_remote(stored, metadata)
    return metadata


def _remote_config() -> tuple[str, str, str] | None:
    url = os.getenv("SUPABASE_URL", "").strip().rstrip("/")
    key = os.getenv("SUPABASE_SECRET_KEY", "").strip()
    bucket = os.getenv("SUPABASE_ARTIFACT_BUCKET", "texdev-artifacts").strip()
    return (url, key, bucket) if url and key else None


def _storage_headers(key: str, content_type: str) -> dict[str, str]:
    return {"apikey": key, "Content-Type": content_type, "x-upsert": "false"}


def _upload_remote(path: Path, metadata: dict) -> None:
    config = _remote_config()
    if not config:
        if os.getenv("VERCEL"):
            raise RuntimeError("Persistent TexDEV downloads are not configured. Set the Supabase server key in the deployment environment.")
        return
    url, key, bucket = config
    root = f"{url}/storage/v1/object/{quote(bucket, safe='')}"
    file_response = requests.post(f"{root}/{quote(metadata['storage_path'], safe='/')}", headers=_storage_headers(key, MIME_TYPES.get(path.suffix.lower().lstrip('.'), "application/octet-stream")), data=path.read_bytes(), timeout=(8, 30))
    file_response.raise_for_status()
    metadata_response = requests.post(f"{root}/{quote(metadata['id'] + '.json', safe='/')}", headers=_storage_headers(key, "application/json"), data=json.dumps(metadata).encode("utf-8"), timeout=(8, 20))
    metadata_response.raise_for_status()


def load_artifact(artifact_id: str) -> tuple[bytes, dict] | None:
    if not re.fullmatch(r"[0-9a-f]{32}", artifact_id or ""):
        return None
    config = _remote_config()
    if config:
        url, key, bucket = config
        root = f"{url}/storage/v1/object/{quote(bucket, safe='')}"
        headers = {"apikey": key}
        response = requests.get(f"{root}/{quote(artifact_id + '.json', safe='/')}", headers=headers, timeout=(8, 20))
        if response.status_code == 404 or (response.status_code == 400 and response.json().get("error") == "not_found"):
            return None
        response.raise_for_status()
        metadata = response.json()
        storage_path = metadata.get("storage_path")
        if not isinstance(storage_path, str) or not storage_path.startswith(artifact_id + "."):
            return None
        content = requests.get(f"{root}/{quote(storage_path, safe='/')}", headers=headers, timeout=(8, 30))
        if content.status_code == 404:
            return None
        content.raise_for_status()
        return content.content, metadata
    resolved = resolve_artifact(artifact_id)
    if not resolved:
        return None
    path, metadata = resolved
    return path.read_bytes(), metadata


def resolve_artifact(artifact_id: str) -> tuple[Path, dict] | None:
    if not re.fullmatch(r"[0-9a-f]{32}", artifact_id or ""):
        return None
    metadata_path = (ARTIFACT_DIR / f"{artifact_id}.json").resolve()
    if metadata_path.parent != ARTIFACT_DIR or not metadata_path.is_file():
        return None
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        extension = Path(metadata["filename"]).suffix.lower().lstrip(".")
        file_path = (ARTIFACT_DIR / f"{artifact_id}.{extension}").resolve()
        if file_path.parent != ARTIFACT_DIR or not file_path.is_file():
            return None
        return file_path, metadata
    except (OSError, ValueError, KeyError, TypeError):
        return None
